// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2ahRKfKdZSY6yy3xUr5wPgZaR2DBinXk',
    appId: '1:1095113480611:web:85b01ee87670c7ede3e216',
    messagingSenderId: '1095113480611',
    projectId: 'mind-sync-4pp',
    authDomain: 'mind-sync-4pp.firebaseapp.com',
    storageBucket: 'mind-sync-4pp.firebasestorage.app',
    measurementId: 'G-5G64W9BSS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHxY9swoj_34PycU3gD-vM5QSp-cBlZpc',
    appId: '1:1095113480611:android:2494c97c1ffe2e92e3e216',
    messagingSenderId: '1095113480611',
    projectId: 'mind-sync-4pp',
    storageBucket: 'mind-sync-4pp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZjjMUvlTVisBTEf6RI-hc0NQQ12neZNY',
    appId: '1:1095113480611:ios:199152a8e3930819e3e216',
    messagingSenderId: '1095113480611',
    projectId: 'mind-sync-4pp',
    storageBucket: 'mind-sync-4pp.firebasestorage.app',
    iosBundleId: 'com.example.mindsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZjjMUvlTVisBTEf6RI-hc0NQQ12neZNY',
    appId: '1:1095113480611:ios:199152a8e3930819e3e216',
    messagingSenderId: '1095113480611',
    projectId: 'mind-sync-4pp',
    storageBucket: 'mind-sync-4pp.firebasestorage.app',
    iosBundleId: 'com.example.mindsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2ahRKfKdZSY6yy3xUr5wPgZaR2DBinXk',
    appId: '1:1095113480611:web:14050de0d8a618efe3e216',
    messagingSenderId: '1095113480611',
    projectId: 'mind-sync-4pp',
    authDomain: 'mind-sync-4pp.firebaseapp.com',
    storageBucket: 'mind-sync-4pp.firebasestorage.app',
    measurementId: 'G-T5ZFCP3YBN',
  );
}
